mode: auto

favicon: /C.png

social:
  - name: GitHub
    link: https://github.com/Cccc-owo
    icon: ri:github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:4hhhhfor@gmail.com
    icon: ri:mail-line
    color: "#8E71C1"

banner:
  enable: true
  title:
    - Cccc_
    - çš„
    - åšå®¢
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur
  
medium_zoom: true

avatar:
  enable: true
  url: /C.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ‘
    message: Nothing.

menu:
  custom:

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

reward:
  enable: false

footer:
  since: 2020
  icon:
    name: ri-ancient-gate-fill
    animated: true
    color: "#0078E7"
    url: 
    title: Oh,you are here.
  powered:
    enable: true
  beian:
    enable: false

mourn:
  enable: true
  days: #month-day
    - "4-4" #http://www.gov.cn/zhengce/content/2020-04/03/content_5498474.htm
    - "9-18"

comment:
  enable: true
  tips:
    - 
  candidates:
     - waline
#    - utterances

waline:
  enable: true
  serverURL: https://blog-chat.iscccc.eu.org/
  # visitor: true
  comment: false

utterances:
  enable: false
  repo: Cccc-owo/blog-related
  issue-term: pathname
  # label: comment
  theme: github-light

engine_search:
  enable: false

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true

wordcloud:
  enable: true
  height: 350

wordcount:
  enable: true
  count: true
  time: true

google_analytics:
  enable: true
  id: G-0CM1PL8163

baidu_push: true

vendors:
  # ä»¥ '/' ç»“å°¾
  host: 'https://npm.elemecdn.com/'
  # ä¸‹æ–¹ä»£è¡¨è¦†ç›– waline CDN ä¸ºåˆ«çš„é“¾æ¥ï¼Œé»˜è®¤ä¸ç”¨ä¿®æ”¹
  # waline:
  #   css: '@waline/client@v2/dist/waline.css'
